### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Freed-Wu** [Lereena/yacc-to-tree-sitter#1]
Example: https://github.com/tmux/tmux/blob/master/cmd-parse.y

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.base/java.util.Collections$SingletonList.get(Collections.java:5180)
        at MainKt.convert(main.kt:44)
        at MainKt.main(main.kt:14)
```

**Comment by HeikoRibberink** [comment]
I have the same problem using [Koka's grammar](https://github.com/koka-lang/koka/blob/f627c2099bd455030abeb7537d38b675437d0e47/doc/spec/grammar/parser.y).

**Comment by HeikoRibberink** [comment]
For anyone interested in a working yacc to treesitter converter, see [heikoribberink/yacc-to-ts](https://github.com/heikoribberink/yacc-to-ts)
